name: Build GKI 6.6 KernelSU-Next

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048

      - name: Build GKI Kernel via Auto-GKI Engine
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://android.googlesource.com/kernel/common
          kernel-branch: android15-6.6
          android-version: android15
          aosp-clang: true
          aosp-clang-version: r510928
          aosp-gcc: true
          ksu: true
          ksu-version: main
          ksu-url: https://github.com/KernelSU-Next/KernelSU-Next.git

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GKI-6.6-KernelSU-Next
          path: |
            android-kernel/arch/arm64/boot/Image
            boot.img
            *.img
